spring:
  application:
    name: configuration_server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/carlosvelascomillan/microservices.git
          search-paths:
            - "configuration_server_repository/{application}/{profile}"
        # username:
        # password:

server:
  port: 8888