spring:
  application:
    name: configuration_server
  cloud:
    config:
      server:
        git:
          uri: file:///C:/Users/21684500P/Desktop/curso/proyectoFuturs/config-repo/
        # username:
        # password:

server:
  port: 8888